import type { Metadata } from "next";

import { LayoutClient } from "@/app/LayoutClient";

import { InternetProvider } from "@/components/providers/internet";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className='font-sans antialiased'>
                <Toaster position="top-right" />
                <InternetProvider>
                    <LayoutClient>
                        {children}
                    </LayoutClient>
                </InternetProvider>
            </body>
        </html>
    );
}
